/// Flutter icons JoinBurarry
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  JoinBurarry
///      fonts:
///       - asset: fonts/JoinBurarry.ttf
///
///
///
import 'package:flutter/widgets.dart';

class JoinBurarry {
  JoinBurarry._();

  static const _kFontFam = 'JoinBurarry';

  static const IconData joinBurarry = IconData(0xe801, fontFamily: _kFontFam);
}
