/// Flutter icons StopBurarry
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  StopBurarry
///      fonts:
///       - asset: fonts/StopBurarry.ttf
///
///
///
import 'package:flutter/widgets.dart';

class StopBurarry {
  StopBurarry._();

  static const _kFontFam = 'StopBurarry';

  static const IconData stopBurarry = IconData(0xe802, fontFamily: _kFontFam);
}
