name: stamp_rally
description: スタンプラリー
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  cloud_firestore: ^3.5.1
  # List 系の拡張されたメソッド (例 firstWhereOrNull) を使いたいため
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.0
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  # Widget 間の余白の入力が楽になるため
  gap: ^2.0.0
  go_router: ^5.1.1
  json_serializable: ^6.5.4
  # ロガーパッケージ
  package_info_plus: ^3.0.2
  roggle: ^0.3.0

dependency_overrides:
  firebase_core_platform_interface: ^4.5.1

dev_dependencies:
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0+1
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.0.15
  # 厳しめの Linter
  pedantic_mono: ^1.20.0

flutter_gen:
  output: lib/util/assets/
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
