name: stamp_rally
description: スタンプラリー
publish_to: 'none'
version: 0.0.1+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  pedantic_mono: ^1.20.0

dependency_overrides:
  firebase_core_platform_interface: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
