// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABW3YAFe6Qej81_cUDw9BcXNFmfiWfkJc',
    appId: '1:801823217631:android:7c65837b1753003e94166a',
    messagingSenderId: '801823217631',
    projectId: 'flutteruniv-stamp-rally-prod',
    storageBucket: 'flutteruniv-stamp-rally-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv_AiAtaPek3FaSCv_qm00nzk6e_Y3c5w',
    appId: '1:801823217631:ios:565923cf929fe9ea94166a',
    messagingSenderId: '801823217631',
    projectId: 'flutteruniv-stamp-rally-prod',
    storageBucket: 'flutteruniv-stamp-rally-prod.appspot.com',
    iosClientId: '801823217631-ofu75sbf4i923bev35igtphlrd58i41a.apps.googleusercontent.com',
    iosBundleId: 'jp.keishimizu26629.stamp-rally',
  );
}
